packages:
  - "frontend"
  - "backend"
  - "shared"
allowBuilds:
  '@apollo/protobufjs': false
  core-js: false
  esbuild: false
  puppeteer: false

  minimumReleaseAge: 4320

  onlyBuiltDependencies: []
  ignoredBuiltDependencies: []
  strictDepBuilds: true
