import { pool } from "../../../config/db.js";
import { ensureQuoteItemDiscountColumnsAction } from "./ensureQuoteItemDiscountColumns.action.js";

export const requestQuoteAction = async (input, user) => {
  // User is the contact here
  const { items } = input;
  const client_id = user.clientId;
  const contact_id = user.contactId;
  let supportsDiscountColumns = false;

  try {
    supportsDiscountColumns = await ensureQuoteItemDiscountColumnsAction();
  } catch (error) {
    console.warn(
      "No se pudieron asegurar columnas de descuento en quote_items:",
      error.message,
    );
  }

  const connection = await pool.getConnection();

  try {
    await connection.beginTransaction();

    // 1. Calculate totals (internal use, even if user doesn't see them yet)
    let quoteTotal = 0;
    const finalItems = [];

    for (const item of items) {
      const [rows] = await connection.query(
        "SELECT id, name, current_price FROM products WHERE id = ?",
        [item.product_id],
      );
      if (rows.length === 0) {
        throw new Error(`Producto con ID ${item.product_id} no encontrado`);
      }
      const product = rows[0];
      const quantity = Math.max(1, Number(item.quantity) || 1);
      const base_unit_price = Number(product.current_price);
      const discount = 0;
      const unit_price = Number(base_unit_price.toFixed(2));
      const lineTotal = Number((unit_price * quantity).toFixed(2));

      quoteTotal += lineTotal;
      finalItems.push({
        product_id: product.id,
        quantity,
        base_unit_price,
        unit_price,
        discount,
        total: lineTotal,
      });
    }

    quoteTotal = Number(quoteTotal.toFixed(2));

    // 2. Insert quote
    // user_id is NULL because it's self-generated by contact
    const [resQuote] = await connection.query(
      `INSERT INTO quotes (client_id, contact_id, user_id, total, notes, status, is_sent_to_client_portal) 
       VALUES (?, ?, NULL, ?, ?, 'REQUESTED', 1)`,
      [
        client_id,
        contact_id,
        quoteTotal,
        "Solicitud de cotización desde Portal de Contacto",
      ],
    );
    const quoteId = resQuote.insertId;

    // 3. Insert items
    for (const item of finalItems) {
      if (supportsDiscountColumns) {
        await connection.query(
          `INSERT INTO quote_items (quote_id, product_id, quantity, base_unit_price, unit_price, discount, total) VALUES (?, ?, ?, ?, ?, ?, ?)`,
          [
            quoteId,
            item.product_id,
            item.quantity,
            item.base_unit_price,
            item.unit_price,
            item.discount,
            item.total,
          ],
        );
      } else {
        await connection.query(
          `INSERT INTO quote_items (quote_id, product_id, quantity, unit_price, total) VALUES (?, ?, ?, ?, ?)`,
          [
            quoteId,
            item.product_id,
            item.quantity,
            item.unit_price,
            item.total,
          ],
        );
      }
    }

    await connection.commit();

    return {
      id: quoteId,
      client_id,
      contact_id,
      user_id: null,
      total: quoteTotal,
      status: "REQUESTED",
      notes: "Solicitud desde portal",
      created_at: new Date(),
      items: finalItems,
    };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    connection.release();
  }
};
