ALTER TABLE quotes
  MODIFY COLUMN status ENUM(
    'PENDING',
    'SENT',
    'ACCEPTED',
    'REJECTED',
    'REQUESTED',
    'PENDIENTE',
    'ENVIADA',
    'ACEPTADA',
    'RECHAZADA',
    'SOLICITADA'
  ) DEFAULT 'PENDIENTE';

UPDATE quotes
SET status = CASE status
  WHEN 'PENDING' THEN 'PENDIENTE'
  WHEN 'SENT' THEN 'ENVIADA'
  WHEN 'ACCEPTED' THEN 'ACEPTADA'
  WHEN 'REJECTED' THEN 'RECHAZADA'
  WHEN 'REQUESTED' THEN 'SOLICITADA'
  ELSE status
END;

ALTER TABLE quotes
  MODIFY COLUMN status ENUM(
    'PENDIENTE',
    'ENVIADA',
    'ACEPTADA',
    'RECHAZADA',
    'SOLICITADA'
  ) DEFAULT 'PENDIENTE';
