CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  folio VARCHAR(30) NULL,
  quote_id INT NOT NULL,
  client_id INT NOT NULL,
  contact_id INT NULL,
  user_id INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  notes TEXT NULL,
  status ENUM('GENERADA', 'ENVIADA') NOT NULL DEFAULT 'GENERADA',
  email_sent_at DATETIME NULL,
  is_sent_to_client_portal TINYINT NOT NULL DEFAULT 0,
  portal_sent_at DATETIME NULL,
  is_deleted_admin TINYINT NOT NULL DEFAULT 0,
  is_deleted_portal TINYINT NOT NULL DEFAULT 0,
  INDEX idx_sales_quote_id (quote_id),
  INDEX idx_sales_client_id (client_id),
  INDEX idx_sales_contact_id (contact_id),
  INDEX idx_sales_user_id (user_id),
  UNIQUE KEY uq_sales_folio (folio),
  CONSTRAINT fk_sales_quotes FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
  CONSTRAINT fk_sales_clients FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_sales_contacts FOREIGN KEY (contact_id) REFERENCES client_contacts(id) ON DELETE SET NULL,
  CONSTRAINT fk_sales_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sale_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sale_id INT NOT NULL,
  quote_item_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  base_unit_price DECIMAL(10,2) NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  discount DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  total DECIMAL(10,2) NOT NULL,
  INDEX idx_sale_items_sale_id (sale_id),
  INDEX idx_sale_items_quote_item_id (quote_item_id),
  INDEX idx_sale_items_product_id (product_id),
  UNIQUE KEY uq_sale_items_quote_item_id (quote_item_id),
  CONSTRAINT fk_sale_items_sales FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
  CONSTRAINT fk_sale_items_quote_items FOREIGN KEY (quote_item_id) REFERENCES quote_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_sale_items_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
